### ISSUE TITLE
Seem to have to use "--" to pass an argument?

### ISSUE THREAD

**Issue by jsmarsch** [gsscoder/commandline#108]
I'm using version 1.9.71 (latest from nuget as of today).  I'm a fairly new user, so maybe I'm doing something wrong, but I found that it only parses successfully if each arguement is passed with a double dash, like:

myApp --arg1 value --arg2 value etc.

I can do that, but it seems kind of unusual.  Most users are used to either a single dash or a forward slash to specify args.  Is there a way to change that behavior?

if it helps, here is a snippet of my option class:

class CommandLineOptions
    {
        [Option("longname", Required=true, HelpText="blah")]
        public string TheProperty { get; set; }

**Comment by gsscoder** [comment]
In 2.0 is even simpler hack the code.
To change `-` \ `--` to `/` for example, just modify: 
https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/Tokenizer.cs

Or better, hack **Parser.cs** and supply it your tokenize function.

If you want stop processing for special `/?` or `-?`, just add an handler here:
https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/PreprocessorGuards.cs

OK? I close the issue for now. Thanks everyone for nice discussion! :+1:

**Comment by Ehryk** [comment]
@gsscoder, my goal in this is not to 'hack the code' in a one-off sense, I'm asking if '/' can be added to the Tokenizer for the main trunk, by default. If you would accept the pull request I will create one and test it, but I'm essentially asking why '/a', '/b', '/?' can't be by default interpreted as '-a', '-b', '--help'?

This is coming from a windows-centric mindset, where arguments are frequently prefaced with /.

**Comment by nemec** [comment]
@Ehryk I don't think that this request will ever make it in as the "Windows" style wouldn't work with some features integral to the "getopt" style -- namely, short name merging (`-ab` instead of `-a -b`).

While it's possible from a technical perspective, this project strives to adhere to the getopt style of parameter passing and a Windows-centric style parser might be better off as a separate project. Windows-style parsing has its own [methods of escaping and delimiting](http://ss64.com/nt/syntax-esc.html) that I would expect to be included in a good library but are incompatible with getopt.

**Comment by Ehryk** [comment]
Why couldn't it support proper getopt, with forward slashes too? For example, `/ab` working the same as `-ab`? I suppose that it would conflict with `/p` as a path from the Linux root, is that why? It does seem a more natural fit for a .NET project.

**Comment by nemec** [comment]
That would work, but I assume you want to support long names with a single slash, too, rather than a double slash.

    class Opts
    {
        [Option('a', "ab")]
        public bool Abs { get; set; }

        [Option('b', "boots")]
        public bool Boots { get; set; }
    }

This would have an ambiguous definition when using `/ab`.

**Comment by gsscoder** [comment]
@Ehryk, `getopt()` supports `/` slashes? It's new to me... Can I have the link?

**Comment by Ehryk** [comment]
@gsscoder no, `getopt()` does not support `/` slashes. I'm asking for an extension on `getopt()` for windows usage (more in line with this being a .NET project).

@nemec I'm completely happy with a hybrid approach: `/ab` = `-ab` and `//long` = `--long` (I.E. `/` just being an allowed variant of `-`).

The only issue I see here is non-Windows pathing: `blah.exe /i /var/log/file.txt`, so I think this would be best implemented as an option that could be disabled: allow `-`,`--` only (default), `/`,`//` only, or either one `/`,`-`,`//`,`--`.

**Comment by nemec** [comment]
@Ehryk in that case I have a many fewer objections. The double slash looks weird to me but as long as the documentation is clear that it only affects the argument delimiter and otherwise parsing is the same, I don't see why it couldn't be added.

For `/?` we should make the Preprocessor Guards for Help and Version configurable (both long and short) so that you could add your own short name of `?`  -- of course stuff like `myapp.exe /a?b` will be legal, but you can probably live with that.

Under non-Windows, you could add your own OS detection and choose the flag delimiter based on that. Unfortunately, you can't quote the path before executing because cmd/ps will do some lexing for you.

`myapp.exe /i "/var/log/file"` becomes the args array `string[]{"/i", "/var/log/file"}` with no way to tell it was quoted unless you use `System.Environment.CommandLine` and split it yourself.

**Comment by gsscoder** [comment]
agree with @nemec about `//` double slash, but I think that I've to surrender and support Windows style syntax due too various requests

now, @Ehryk, the point is to define a new standard or in library internals a new `Tokenizer`

@nemec, will be agree with me that a possible solution could be add boolean property in `ParserSettings` that will switch to a future `WindowsTokenizer`

on a thing I'm sure: I'm against to allow hybrid between *nix and Windows syntax!
