### ISSUE TITLE
Wiki/ReadMe Seems to be outdated.

### ISSUE THREAD

**Issue by prasannavl** [gsscoder/commandline#124]
It seems the ParseArguments<OptionType> is no longer available, and the ParserState is no longer returned to extract the errors.

**Comment by gsscoder** [comment]
@prasannavl, in this "issue" there are clarifications about main versions and their documentation: https://github.com/gsscoder/commandline/issues/131.

As you can read from this small [wiki](https://github.com/gsscoder/commandline/wiki/Latest-Version) section (we're still talking of a pre-release) available for that version, `ParserResult<T>` will hold the parsed instance in the `Value` property. (Sample in unit tests -> https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/ParserTests.cs#L62).

Generally the library will handle the help screen for you, so you can just check the `IEnumerable<Error>` list exposed via `Errors` property and consume the `Value` with your typed parsed instance only if such list is empty.

@nemec, I've chose this design because the library always build up an instance of supplied `<T>` for your options. The alternative would have been returning a `null`, but since 2.0 pre-rel kernel was refactored to be more functional (limited to both C# allows and over all my current skills) this path was discarded at speed of light.

A possible better implementation could be model that type like an F# discriminated union (see this my [blog post](http://gsscoder.github.io/2013/04/23/discriminated-unions-in-c/)). In such case a subtype will contain always a valid `T Value` instance and the other an `IEnumerable<Errors> Errors` always with at least one item. For the moment I've opted for a single type for avoid developers simulate pattern matching testing the simulated discrimination `Tag` property... It's a matter of choice.

I close the issue because is already off-topic... but I'd like to deepen this argument with everyone interested in.
