### ISSUE TITLE
Getting exception from failed parsing

### ISSUE THREAD

**Issue by adamralph** [gsscoder/commandline#126]
In the wiki, this code example is given:

```c#
if (CommandLine.Parser.Default.ParseArgumentsStrict(args, options,
  () => {
    ProperlyDisposeYourResources((ex) => Log.Error(ex.Message));
    Environment.Exit(-2);
  }))
{
  // Domain logic here
}
```

Where does `ex` come from?

**Comment by gsscoder** [comment]
@adamralph, @bastienJS, what @nemec (I think) want to say is that is just sample code, nothing complete: name of method are self-esplicative just for suggest you how to do.
`ex` is the parameter of lambda passed to the hypothetical method (here the confusion arises because `ParseArgumentStrict` accepts parameterless lambda defined as `Action` that calls a method with a lambda with one parameter); but it's perfectly legal C# code.

Nowadays I'll try to reduce `void` returning methods with side effects, but the sample suggest that `ProperlyDisposeYourResources` could be written as 
```csharp
ProperlyDisposeYourResources(Action<Exception> handleExecption) {
  try {
    YourResource.Free();
    YourDB.Close();
    // etc...
  } catch (e) {
    handleException(e);
  }
}
```

@bastienJS, normally the parser will do the job for you, but as describe [here](https://github.com/gsscoder/commandline/wiki/Display-A-Help-Screen) you can manipulate a collect of `Error`s adding the following property to your options class:
```csharp
public interface IParserState { IList<ParsingError> Errors { get; } }
```

All said is true only for 1.9.71.2 stable.
