### ISSUE TITLE
.NET 3.5+ but you use Tuple class in the source code which build only for .NET 4.0 ?

### ISSUE THREAD

**Issue by bastienJS** [gsscoder/commandline#131]
no comment!

**Comment by gsscoder** [comment]
@bastienJS:
- stable version: **stable-1.9.71.2** branch (https://github.com/gsscoder/commandline/tree/stable-1.9.71.2)
- 2.0.x-pre version: **master** branch -> (https://github.com/gsscoder/commandline)

the first time I've staged stable in its branch, I've not updated README.md of pre-release (since it's still a pre-release: I think we can suffer issues, outdated docs or whatever)

Wiki refers to stable: https://github.com/gsscoder/commandline/wiki
except this (still not completed) section about pre-release: https://github.com/gsscoder/commandline/wiki/Latest-Version

it's **ALWAYS** important read documentation for being acquainted on which version is available and its status of development

more over @nemec is right, `Tuple` is a straightforward class to implement (the only real requirement is a C# compiler with generics support)
