### ISSUE TITLE
HelpVerbOptionAttribute broken

### ISSUE THREAD

**Issue by CrescentFresh** [gsscoder/commandline#138]
Piecing together [HelpVerbOption] usage, the below example from the wiki doesn't render anything.

CommandLine 1.9.71 via nuget.

Repro:

    class Options
    {
        public Options()
        {
            // Since we create this instance the parser will not overwrite it
            CommitVerb = new CommitSubOptions();
        }

        [CommandLine.VerbOption("commit", HelpText = "Record changes to the repository.")]
        public CommitSubOptions CommitVerb { get; set; }

        [CommandLine.HelpVerbOption]
        public string GetUsage(string verb)
        {
            return "this never appears";
        }
    }

    class CommitSubOptions
    {
        [CommandLine.Option('a', "all", HelpText = "Tell the command to automatically stage files.")]
        public bool All { get; set; }
        // Remainder omitted
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var options = new Options();
            args = "help commit".Split();
            CommandLine.Parser.Default.ParseArguments(args, options);
            Console.ReadLine();
        }
    }

**Comment by thesolution** [comment]
This issue was corrected in pull request [#74](https://github.com/gsscoder/commandline/pull/74) but was not accepted.  So the options are fork or use something like [ManyConsole](https://github.com/fschwiet/ManyConsole/) if you need verbs.

**Comment by spadfield** [comment]
I would like to see this fix, if possible.

**Comment by nemec** [comment]
[@cosmo0's fork](https://github.com/cosmo0/commandline) accepts pull requests. Unfortunately the dev here disappeared.

**Comment by gsscoder** [comment]
@CrescentFresh, @JMerrill, @spadfield please check if https://github.com/gsscoder/commandline/wiki/Verb-Commands this solves the problem. Since I was away for a while maybe that when you posted wiki was outdated. As for all the rest of the wiki this is about stable.

Latest days (in moment of writing this post) work is proceeded on 2.0 pre-rel, making it more usable (it was really a preview before these times, I know...).

Some info (for the moment not a full wiki) for 2.0 pre-rel can be found here: https://github.com/gsscoder/commandline/wiki/Latest-Version. I've recently added a section about verb commands.

If this not help, please ping; I'm back and I'm here to help!

cc/ @nemec @mizipzor @gimmemoore
