### ISSUE TITLE
Enum option validation allows any int value

### ISSUE THREAD

**Issue by Toeboy** [gsscoder/commandline#149]
Hello,

I'm trying to set an Enum option for System.Diagnostics.TraceLevel and it seems any integer can be inputed and will pass the parsing. For example using:

        [Option('t', Required = false, DefaultValue = TraceLevel.Off, HelpText = "Tracer verbosity switch.")]
        public System.Diagnostics.TraceLevel TraceLevel { get; set; }

and executing with -t 10 switch will work, but TraceLevel enum only contains values from 0 to 4.

Is this normal?

Thanks

TB

**Comment by nemec** [comment]
That's the way enums work (they're just integers underneath).

It's possible to specifically verify a value for an enum, though (the code just doesn't do it): 

    >>> Enum.IsDefined(typeof(TraceLevel), 10)
    False

**Comment by Toeboy** [comment]
Yes. But since they pass the parsing I have to check them with Enum.IsDefined afterwards. I was hoping they would already be checked and add an error to the LastParserState.

**Comment by nemec** [comment]
Yes, I'm just saying that it's normal behavior since the library doesn't validate itself. How would you handle Enums that are also Flags?

Say I have

    [Flags]
	enum Test
	{
		A=1,
		B=2
	}

And I try

    Enum.IsDefined(typeof(Test), 1|2);
    Enum.IsDefined(typeof(Test), 3);

They both return false. I would imagine a feature like this would accept multiple flags as an integer (although when accepting an identifier multi-flag you'd have to create a new enum value like `C=A|B`).

**Comment by Toeboy** [comment]
Good point. I’m currently only using strings, in and simple enums. I wonder how I would input flags on the command line, probably a separate required=false option for each flag value and combine them myself after parsing. 
 
Something like myapp.exe -AB
 
Then after parsing
Enum.IsDefined(typeof(Test), commandLineOptions.A + commandLineOptions.B)
 
What would you recommend?

**Comment by nemec** [comment]
If you have no need for flags in your application, then you don't need to worry about it :)
But if you or anyone else following this issue is thinking of submitting a pull request (and you would want to submit it to @cosmos0's fork), it's something you should think about including.

In my opinion, I'd use these rules:

* Defined == true if all components are defined in the enum.
* Defined == false if a component is present that isn't defined (like 4 isn't defined above and 5: binary 111 isn't defined for the third bit in the test enum either), if that makes sense.

Something like this LINQPad script:

	void Main()
	{
		"With Flags:".Dump();
		(IsDefined(typeof(WithFlags), 1) == true).Dump();
		(IsDefined(typeof(WithFlags), 2) == true).Dump();
		(IsDefined(typeof(WithFlags), 3) == true).Dump();
		(IsDefined(typeof(WithFlags), 1|2) == true).Dump();
		(IsDefined(typeof(WithFlags), 4) == false).Dump();
		(IsDefined(typeof(WithFlags), 7) == false).Dump();
		
		"\r\nWithout Flags:".Dump();
		(IsDefined(typeof(WithoutFlags), 0) == true).Dump();
		(IsDefined(typeof(WithoutFlags), 1) == true).Dump();
		(IsDefined(typeof(WithoutFlags), 3) == false).Dump();
		(IsDefined(typeof(WithoutFlags), 1|2) == false).Dump();
		(IsDefined(typeof(WithoutFlags), 4) == false).Dump();
		(IsDefined(typeof(WithoutFlags), 7) == false).Dump();
		
	}
	
	public bool IsDefined(Type enumType, object value)
	{
		// Not flagged
		if(enumType.GetCustomAttribute<FlagsAttribute>() == null)
		{
			return Enum.IsDefined(enumType, value);
		}
	
		// Only integral types allowed in enums,
		// so casting to the largest. Flags should
		// be positive powers of 2, so unsigned.
		// Cannot cast-convert object to ulong
		// so must convert.
		var remaining = Convert.ToUInt64(value);
		foreach(object obj in Enum.GetValues(enumType))
		{
			var enumValue = Convert.ToUInt64(obj);
			remaining = remaining & ~enumValue;
		}
		return remaining == 0;
	}
	
	[Flags]
	enum WithFlags
	{
		A=1,
		B=2
	}
	
	enum WithoutFlags
	{
		A,
		B
	}

**Comment by gsscoder** [comment]
@Toeboy thank you for that interesting point! I ask the good @nemec if he can check this in the stable branch, while I write a test for 2.0 pre-rel.

cc/ @mizipzor @gimmemoore

**Comment by gsscoder** [comment]
@Toeboy Version 2.0 pre-rel solves this issue, so I close the issue.

Feel free to re-open if this is not true on stable branch or comment if there's also to say about it.

cc/ @nemec @mizipzor @gimmemoore
