### ISSUE TITLE
VerbOption seems to be missing in 2.0.5-pre

### ISSUE THREAD

**Issue by Kimi-Arthur** [gsscoder/commandline#166]
Hi,

I tried to use the nuget package recently with version 2.0.5-pre. According to the docs, I need to specify "VerbOption" for verb options, but that doesn't seem to appear.

What should I do in 2.0.5-pre if I want to the verb command thing?

Thanks!

**Comment by gsscoder** [comment]
Wellcome @Kimi-Arthur, happy of your interest in this library!

The correct attribute is `Verb` not `VerbOption` for **2.0.x-pre** as explained [here](https://github.com/gsscoder/commandline/wiki/Latest-Version). The latter was for the latest stable [1.9.71.2](https://github.com/gsscoder/commandline/tree/stable-1.9.71.2) that lives in its branch.

As the header note on [wiki](https://github.com/gsscoder/commandline/wiki) home states: everything is about latest stable except section **Latest Version** (that refers to pre-release).

If you use 2.0.x-pre from NuGet please be sure to install the very last version as explained in the same section. As you know you can check it from your `packages.config`.

Please let me know if this helped.

**Comment by Kimi-Arthur** [comment]
You mean there is no need for attribute for verb properties inside main options?

class Options
{
    // Nothing here?
    public CopyCommandOption CopyCommand { get; set; }
}

[Verb("cp")]
class CopyCommandOption
{
    [Value(0)]
    public string FromPath { get; set; }
}

**Comment by gsscoder** [comment]
@Kimi-Arthur, no I talking about exact name... First time you said that you can't find `VerbOption` and this is true, because the previous stable used that name, while the new pre-release (that you're using) use an attribute named just `Verb`.

For verbs, you've to define a standard class for each verb you want to support (like stated [here](https://github.com/gsscoder/commandline/wiki/Latest-Version)):
```csharp
[Verb("add", HelpText = "Add file contents to the index.")]
class AddOptions { //normal options here
  [Option, HelpText="..."]
  public bool Version { get; set; }
  // ...
}
[Verb("commit", HelpText = "Record changes to the repository.")]
class CommitOptions { //normal options here
  // ...
}
[Verb("clone", HelpText = "Clone a repository into a new directory.")]
class CloneOptions { //normal options here
  // ...
}
```
Than just invoke the parser with appropriate type parameter overload (without using the variadic overload you can define at least 16 types). If follows an example of invocation:
```csharp
var result = Parser.Default.ParseArguments<AddOptions, CommitOptions, CloneOptions>(args);
if (result.Errors.Any()) {
  Enviornment.Exit(-1);
}
if (result.Value.GetType() == typeof(AddOptions)) {
  var addOptions = (AddOptions)result.Value;
  // consume addOptions here
}
// do the same check and cast for other options classes defined for each verb
```
You don't need to handle help screen generation the library will do it for you. When using verbs (`ParseArguments<T1,T2,...>()` overloads with two types or more) you get an extra verb called `help`. It's capable of displaying or a screen with verbs summary or the one specific to each verb when invoked `yourapp help verbname`.

Let me know if this helped and/or eventually we can close the issue; but if still not clear don't hesitate tell me.

**Comment by Kimi-Arthur** [comment]
I got the problem solved with your great help!

Essentially the verb commands are used in a different way, didn't think of that.

Thanks! :)

**Comment by gsscoder** [comment]
You're welcome.
