### ISSUE TITLE
Cannot parse boolean options

### ISSUE THREAD

**Issue by StevenLiekens** [gsscoder/commandline#238]
Version 2.0.261-beta

My option looks like this

````C#
[Option('t', "trusted", Default = true, SetName = "noconnectionstring", HelpText = "Specify whether the connection uses integrated security.")]
public bool IntegratedSecurity { get; set; }
````

No matter what I try, the parser always sets `ÌntegratedSecurity` to its default value `true`.

> ConsoleApplication.exe -t false
> ConsoleApplication.exe -t False
> ConsoleApplication.exe -t 0

Even if I remove the part `Default = true`, I still get value `true`.

Is this a type conversion bug?

**Comment by StevenLiekens** [comment]
Just a thought, but maybe there should be an extension mechanism for custom type converters. Something along the lines of a custom class that implements a given interface `IArgumentConverter<T>`.

````C#
interface IArgumentConverter<T>
{
    T ConvertArgument(string argument);
}
````

````C#
class BooleanConverter : IArgumentConverter<bool>
{
    bool ConvertArgument(string argument)
    {
        return bool.Parse(argument);
    }
}
````

Then let us inject the type converter using either the `Action<ParserSettings>` delegate or by setting it on the `OptionAttribute` directly.

````C#
var parser = new Parser(
                parserSettings =>
                {
                    parserSettings.TypeConverters[typeof(bool)] = new BooleanConverter();
                });
````

````C#
[Option('t', "trusted", Default = true, ..., TypeConverter = typeof(BooleanConverter))]
public bool IntegratedSecurity { get; set; }
````

**Comment by gsscoder** [comment]
@StevenLiekens, this is covered by a variety of issues. Please check! :)

As in #213, no enhancemente will be added until stable is reached.

**Comment by StevenLiekens** [comment]
Okay but what about the original question? I still can't parse arguments as boolean.

**Comment by gsscoder** [comment]
More references: #115 and #133 for example.

The problem is that the parser has its own logic of parsing booleans directly grasped from `getopt()` \ *nix terminal style.

Having:
```csharp
class Options {
  [Option('v')]
  public bool Verbose { get; set; }
}
```

For the moment you can't explictely set `Verbose` to `false`. This is done, by design, omitting it:
```
$ app
```
But you can enable it explitely:
```
$ app -v
```

In fact this kind of options are internally treated as `Switch`.

Anyway it's possible that after 2.0 reaches `stable` status, I'll add some pre/post processing machinery that will add allow explicit setting of boolean with syntax like `app -v true` or using custom tokens like `app -v+`. (See quoted issues/pr for discussion).

**Comment by StevenLiekens** [comment]
Oh, I get it now. :) Thanks.

**Comment by gsscoder** [comment]
Perfect! :)
