### ISSUE TITLE
CommandLineParser doesn't parse the value properly if there is an '=' in the value.

### ISSUE THREAD

**Issue by jinujoseph** [gsscoder/commandline#262]
Hey Giacomo,
I am using the command line  CommandLineParser package  version="2.0.273-beta"  
When I provide the commandline option with 
myApp.exe  --example1=”portal=https;sample=sample1”;
 It takes only portal as an input for example1 ( I am assuming you split by = and assume none of the values will have = )
How can I escape the = in the commandline argument? 
 Thanks
Jinu

**Comment by gsscoder** [comment]
Hi @jinujoseph,
premising that this could deserve further investigation, I feel confident that you can treat this case as an _option list_. More info here in th [wiki](https://github.com/gsscoder/commandline/wiki/Latest-Version#option-attribute).

Define an `Option` bound to a sequence and set **Separator** to "," ("," is better than ";" since the is also a terminal command), the string will be automatically split by the parser. I also suggest you to use ":" token inside value instead of "=" already used by the parser for explicit long option assignment.

Going from memory, I post an untested snippet of code, that should implement what described:
```csharp
class Options {
  [Option(Separator=",")]
  public IEnumerable<string> Settings { get; set; }
}
```
Than this will allow (all valid):
```bash
$ app --settings=portal:https,sampleA:sample1,xyz:abc
$ app --settings="portal:https,sampleA:sample1,xyz:abc"
$ app --settings portal:https,sampleA:sample1,xyz:abc
$ app --settings "portal:https,sampleA:sample1,xyz:abc"
```
If the value doesn't cotain spaces you can also omit double quote. When you enclose a value into double quote you're forcing the terminal to treat the enclosed characters as single command line argument: this job is done by the terminal, not by the library.

Coming back to our sample your `Options.Settings` sequence will contain 3 values:
```
portal:https
sampleA:sample1
xyz:abc
```
Now normal post-processing code will split these value-key pair and use can use your data in your program logic.

I hope that helped.

**Comment by mizipzor** [comment]
This has been inactive for a while, but it looks like the problem was solved. Can we close this? :)

**Comment by ElanHasson** [comment]
I'm experiencing the same issue-- I need the full value-- why is the library attempting to parse stuff in quotes? In my case, it's a SQL Connection string.

**Comment by nemec** [comment]
@ElanHasson can you share an example? I don't see any issues.

```csharp
void Main()
{
	var result = Parser.Default.ParseArguments<Options>(new[] { "--option", 
         "Server=myServerAddress;Database=myDataBase;User Id=myUsername;" });
	result.WithParsed(o =>
	{
		o.Conn.Dump();
	});
}

class Options
{
	[OptionAttribute('o', "option")]
	public string Conn { get; set;}
}
```

Prints: 

    Server=myServerAddress;Database=myDataBase;User Id=myUsername;
