### ISSUE TITLE
Is it possible to have an undocumented argument

### ISSUE THREAD

**Issue by gfody** [gsscoder/commandline#263]
Like a hidden property for the option attribute?

**Comment by otherdave** [comment]
I'm curious about this as well. If there are no plans, I may try to implement and submit a PR if @gsscoder  would be interested in accepting it?

**Comment by nemec** [comment]
That isn't a feature yet, but I'd be happy to accept it. Maybe an additional attribute you can apply, similar to `UsageAttribute`? There are other options too.

**Comment by otherdave** [comment]
@nemec did you mean in addition to an `[Option(...)]` attribute you'd also have one for visibility?

```c#
[Option("secret_mode", DefaultValue = false, HelpText = "shhhhh"]
[HiddenCommandLineOptionAttribute]
public bool IsSecretMode { get; set; }
```

I didn't know about the UsageAttribute until just now :) I've been looking and using the stable API docs so I'm still getting my head around the 2.0 way of doing things (like specifying the help text for an option!)

**Comment by nemec** [comment]
Yes, although adding an additional property to `UsageAttribute` alongside `ApplicationAlias` as the way to control visibility may be a good idea instead. Since "hidden from usage" applies only to the help display and has nothing to do with parsing, I'd prefer to leave it out of `OptionAttribute`

**Comment by CreepyGnome** [comment]
Hey I like this idea of being able to have hidden verbs and options. 

I would like to suggest my opinion on its implementation.  I think adding a property to the BaseAttribute class called something like Visible or Hidden (depending on preference) with the value defaulting to the Option or Value being shown in help, and the developer would have to "opt-in" to provide the value to hide the whole verb, or only an option.

This would then need to be added to Specification as well, and used most likely (from what I can tell) in HelpText.AddOption method right at the top, where it can check the Specification provided if it should be visible or not, and if it should then continue otherwise just return.  The trick I see would be in the AdaptVerbsToSpecifications so that the NewSwitch method can take a new param for this new state.

If this sounds like a good start to look at I wouldn't mind implementing this feature and submitting a pull request.

**Comment by nemec** [comment]
I like the option for `Hidden=true`. Since booleans are generally false by default, I think most developers would understand that it means options are visible unless explicitly set to hidden. Sounds like a good plan.

**Comment by CreepyGnome** [comment]
Hey if anyone would like to test out this new feature I would appreciate it greatly before its merged to master. I tested it out and created additional unit tests, but a few extra eyes are always useful and appreciated.

**Comment by nemec** [comment]
@CreepyGnome's pull request has been merged. There is now a `Hidden` property on each `OptionAttribute`.

```csharp
[Option("secret-option", Hidden = true, HelpText = "You should never see this.")]
public string SecretOption { get; set; }
```
