### ISSUE TITLE
Nuget release package for 2.0

### ISSUE THREAD

**Issue by zidad** [gsscoder/commandline#264]
Hi,

I'm trying to create a (release) nuget package which depends on your v2 version of CommandLineParser, but I can't as it's only available as a beta. 

Do you have a date v2 will be available as a release package? 

What still needs to happen for this, do you need any help?

Thanks!

**Comment by nemec** [comment]
Hey @zidad, only the project owner has access to the NuGet account and he's on hiatus at the moment. If you're using it at work, you could build it yourself, create a Nuget package out of it, put it on a fileshare somewhere, and then add that fileshare as an additional repository in VS. Since the snk is included in the repository, your custom package should update cleanly. Once 2.0 comes out for real, it should show up as an "update" to your custom-built package.

**Comment by zidad** [comment]
Hi Dan, thanks for the tip! Actually repackaging it as release package is what I've done a while ago and it works great...  :)

**Comment by mizipzor** [comment]
Problem solved then? If so, can we close this? :)

**Comment by zidad** [comment]
will do, though I can imagine I'm not the only one with the issue :)

**Comment by mizipzor** [comment]
It has indeed been brought up before. I would also like to see it happen. I could try reach out to the owner, see if maybe he can grant one of us collaborators access to the Nuget keys.
