### ISSUE TITLE
how default argument to be parsed?

### ISSUE THREAD

**Issue by slaner** [gsscoder/commandline#296]
What if application has default argument(no short/long name), how to parse it ?

[Option('', "", ... << like this?

structure are like this:
app [options] <argument>

**Comment by nemec** [comment]
Hi @slaner sorry I missed seeing this issue. You're looking for something like this?

    xcopy C:\myfile.doc C:\myfile-backup.doc

Instead of the `Option` attribute, use the `Value` attribute, like in [this example](https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Fakes/Simple_Options_With_Values.cs#L7). You can see how it's used [here](https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/ParserTests.cs#L113).

**Comment by slaner** [comment]
@nemec thanks for your answer, btw I solved this problem this way:
`
[ValueList(typeof(List<string>))]
public List<string> In { get; set; }
`
