### ISSUE TITLE
Limited to 16 verbs

### ISSUE THREAD

**Issue by claunia** [gsscoder/commandline#300]
Please remove the limit to 16 different generic types.
I used 18 verbs easily in before the change to generic types without a problem and this prevents me to migrate to your last version.

**Comment by claunia** [comment]
#301 helps, but ideal should be no limits.

**Comment by nemec** [comment]
Is there a reason you can't use the overload that takes [type arguments](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Parser.cs#L147)? Generics with a large number of types get very unwieldy to pass around and with type arguments you can put them all in an array to pass around wherever you need them.

There are also no limits to how many types you can pass in, unlike generics which are enforced by the compiler. We could add 128 or more generic arguments, but since generics are determined at compile time you're never going to be able to have "unlimited" verbs.

**Comment by nemec** [comment]
I'm going to close this for now, but if you have the time I am interested in hearing whether the alternative I outlined above will work for you.
