### ISSUE TITLE
case insensitive parsing fails

### ISSUE THREAD

**Issue by attilah** [gsscoder/commandline#92]
I've casesensitive=false in the settings, but parsing a lowercase enum value fails, because the TypeConverter does not look at this setting and not using for parsing an enum value.

**Comment by gsscoder** [comment]
https://github.com/gsscoder/commandline/pull/95 merged

**Comment by vadim82** [comment]
This doesn't seem to work in version 2.0.275-beta. Is this now done differently?

**Comment by nemec** [comment]
@vadim82 I don't believe CommandLine ever supported custom converters. [TypeConverter](https://github.com/gsscoder/commandline/search?utf8=%E2%9C%93&q=converter&type=Code) is used but that doesn't support anything custom.

**Comment by joerg-frech** [comment]
What about _ParserSettings.CaseInsensitiveEnumValues_? This should produce the desired behavior, but it doesn't work (in 2.0.275-beta), if used in conjunction with verbs.

The following fails with an _ArgumentException_ ("Requested value 'json' was not found") in _TypeConverter.ToEnum()_:
`createpackage --format json`
Here _createpackage_ is the verb and the Enum member is _FileFormat.Json_.

The culprit seems to be the literal _false_ in [line 63 of InstanceChooser.MatchVerb()](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/InstanceChooser.cs#L63):

```csharp
    47  private static ParserResult<object> MatchVerb(
    48      Func<IEnumerable<string>, IEnumerable<OptionSpecification>, Result<IEnumerable<Token>, Error>> tokenizer,
    49      IEnumerable<Tuple<Verb, Type>> verbs,
    50      IEnumerable<string> arguments,
    51      StringComparer nameComparer,
    52      CultureInfo parsingCulture,
    53      IEnumerable<ErrorType> nonFatalErrors)
    54  {
    55      return verbs.Any(a => nameComparer.Equals(a.Item1.Name, arguments.First()))
    56          ? InstanceBuilder.Build(
    57              Maybe.Just<Func<object>>(
    58                  () =>
    59                      verbs.Single(v => nameComparer.Equals(v.Item1.Name, arguments.First())).Item2.AutoDefault()),
    60              tokenizer,
    61              arguments.Skip(1),
    62              nameComparer,
    63              false,
    64              parsingCulture,
    65              nonFatalErrors)
    66          : MakeNotParsed(verbs.Select(v => v.Item2), new BadVerbSelectedError(arguments.First()));
    67  }
```
This _false_ ends up as the _ignoreValueCase_ argument of _TypeConverter.ToEnum()_, which leads to the mentioned exception.

Could anybody please have a look into this?

**Comment by Virtlink** [comment]
This is also an issue for me. I need case-insensitive parsing of enum names to values.
